services:
  portal:
    build: .
    container_name: thermoduct-portal
    env_file:
      - .env
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portal.rule=Host(`portal.thermoduct.elementium.be`)"
      - "traefik.http.routers.portal.entrypoints=websecure"
      - "traefik.http.services.portal.loadbalancer.server.port=80"

networks:
  default:
    name: traefik
    external: true
